# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Update README

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm ci
    - run: npm run update
    - name: Add & Commit
      uses: EndBug/add-and-commit@v4.2.1
      with:
        add: README.md
        message: 'Updating README'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#     - run: npm ci
#     - run: npm run build --if-present
#     - run: npm test
