name: Update README

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:
  push:
    paths:
    - scripts/README.template.md
    - scripts/update.js
    - package.json
    - package-lock.json

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm ci
    - run: npm run update
    - name: Add & Commit
      uses: EndBug/add-and-commit@v4.2.1
      with:
        add: README.md
        message: 'Updating README'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
